### ISSUE TITLE
Change log does not indicate data update because it is not done as PRs

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-iers-data#16]
See https://github.com/astropy/astropy-iers-data/releases/tag/v0.2023.07.06.21.08.44

Would be more useful if the change log says which files changed but it only auto generate from PRs and file updates are done directly to `main`.

🤷

**Comment by astrofrog** [comment]
If we really care about adding this to the generated changelog, what we could do is that since we are using:

https://github.com/softprops/action-gh-release

we could set ``body`` to a sentence saying that the files were updated to the latest version as of the release date (which is true if the release workflow runs) and then set ``append_body`` to ``true`` so that the generated release notes include  the usual.

**Comment by pllim** [comment]
Let's see how confusing it gets going forward once the infrastructure is already in place.

**Comment by pllim** [comment]
I think it is fine when we don't have PRs lol

https://github.com/astropy/astropy-iers-data/releases/tag/v0.2023.07.10.00.36.50
